services:
  discord-bot:
    build: .
    container_name: discord-bottest
    restart: unless-stopped
    
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - CONTROL_CHANNEL=${CONTROL_CHANNEL:-server-control}
      - SERVERS_YAML=${SERVERS_YAML}
      - SERVERS_JSON=${SERVERS_JSON}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge